version: "3.4"
services:
    geoip-rs:
        container_name: ${APP_CONTAINER_NAMESPACE:-}geoip-rs
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            target: runtime
            args:
                GEOLIGHT_RELEASE: ${GEOLIGHT_RELEASE:-latest}
        ports:
            - 127.0.0.1:${APP_GEOIP_PORT:-8080}:8080
